import requests
import json 

token = "eyJhbGciOiJFUzI1NiIsImp3ayI6eyJjcnYiOiJQLTI1NiIsImt0eSI6IkVDIiwieCI6InozMFd1eHBzUG93OEtwSDBOOTN2VzI0bkEwSEQ0OF9NbHVxZ2RFVXZ0VTQiLCJ5IjoiVmNLY28xMkJaRlB1NUhVMkxCTG90VEQ5Tml0ZGxOeG5CTG5nRC1lVGFwTSJ9LCJ0eXAiOiJqd3QifQ.eyJhdWQiOiJodHRwczovL3plcm8uY2xvdWQiLCJpc3MiOiJodHRwOi8vdGVzdHNjcmlwdCIsInZjIjp7IkBjb250ZXh0IjpbImh0dHBzOi8vd3d3LnczLm9yZy8yMDE4L2NyZWRlbnRpYWxzL3YxIiwiaHR0cHM6Ly9tbS5hdWViLmdyL2NvbnRleHRzL2NhcGFiaWxpdGllcy92MSJdLCJjcmVkZW50aWFsU3ViamVjdCI6eyJjYXBhYmlsaXRpZXMiOnsiaHR0cHM6Ly96ZXJvLmNsb3VkIjpbIkZMX1JFQUQiLCJGTF9XUklURSJdfX0sInR5cGUiOlsiVmVyaWZpYWJsZUNyZWRlbnRpYWwiLCJDYXBhYmlsaXRpZXNDcmVkZW50aWFsIl19fQ.d5z2ycUQbqAF0ObhZHweEoWRLAss6h48seMLbkNeeXzjoNqc7XT2yWwA63Nf8D7NKO3mOkPOHSbHpPE9wb6xBA"
headers = {'Authorization':'Bearer ' + token, 'Accept': 'application/json'}
response  = requests.get("http://localhost:9000/secure/no-proxy-jwt-vc", headers = headers)
print(response.text)
